version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mapas_gr_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
